version: '3.8'
services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    environment:
      LIVEKIT_KEYS: "devkey: devsecret"
    networks:
      - livekit-net

networks:
  livekit-net:
    driver: bridge
