import { sql } from "drizzle-orm"
import {
  serial,
  pgTable,
  text,
  integer,
  timestamp,
  jsonb,
  numeric,
  index,
  uniqueIndex,
  check,
} from "drizzle-orm/pg-core"
import { createInsertSchema, createSelectSchema } from "drizzle-zod"
import { z } from "zod"
import { chats } from "./chats"
import { messages } from "./messages"

/**
 * Agent Documents Table
 * Stores synthetic documents generated by delegated agents during chat conversations.
 * These documents serve as first-class citations that can be viewed and referenced.
 */
export const agentDocuments = pgTable(
  "agent_documents",
  {
    id: serial("id").notNull().primaryKey(),
    externalId: text("external_id").unique().notNull(),
    chatId: integer("chat_id")
      .notNull()
      .references(() => chats.id, { onDelete: "cascade" }),
    messageId: integer("message_id").references(() => messages.id, { onDelete: "set null" }),
    agentId: text("agent_id").notNull(),
    agentName: text("agent_name").notNull(),
    content: text("content").notNull(),
    summary: text("summary"),
    reasoning: text("reasoning"),
    citations: jsonb("citations").default(sql`'[]'::jsonb`),
    confidence: numeric("confidence", { precision: 3, scale: 2 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`NOW()`),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => ({
    agentDocChatIdIndex: index("agent_doc_chat_id_index").on(table.chatId),
    agentDocMessageIdIndex: index("agent_doc_message_id_index").on(table.messageId),
    agentDocExternalIdIndex: uniqueIndex("agent_doc_external_id_unique_index").on(
      table.externalId,
    ),
    agentDocAgentIdIndex: index("agent_doc_agent_id_index").on(table.agentId),
    confidenceCheck: check("agent_doc_confidence_check", sql`${table.confidence} >= 0 AND ${table.confidence} <= 1`),
  }),
)

// Citation reference schema for documents that the agent used
export const agentCitationReferenceSchema = z.object({
  docId: z.string(),
  title: z.string(),
  url: z.string().optional(),
  app: z.string(),
  entity: z.string(),
  chunkContent: z.string().optional(),
})

export type AgentCitationReference = z.infer<typeof agentCitationReferenceSchema>

// Insert schema
export const insertAgentDocumentSchema = createInsertSchema(agentDocuments, {
  citations: z.array(agentCitationReferenceSchema).nullable().optional().default([]),
  confidence: z.number().min(0).max(1).nullable().optional(),
}).omit({
  id: true,
  createdAt: true,
})

export type InsertAgentDocument = z.infer<typeof insertAgentDocumentSchema>

// Select schema
export const selectAgentDocumentSchema = createSelectSchema(agentDocuments, {
  citations: z.array(agentCitationReferenceSchema).nullable().optional().default([]),
  confidence: z.number().min(0).max(1).nullable().optional(),
})

export type SelectAgentDocument = z.infer<typeof selectAgentDocumentSchema>

// Public schema (for API responses) - excludes internal IDs
export const selectPublicAgentDocumentSchema = selectAgentDocumentSchema.omit({
  id: true,
  chatId: true,
  messageId: true,
})

export type SelectPublicAgentDocument = z.infer<typeof selectPublicAgentDocumentSchema>
