import { pgTable, serial, varchar, text, integer, timestamp } from "drizzle-orm/pg-core"

/**
 * Stores individual thread/comment summaries as they're generated by LLM
 * Each row represents one thread or comment summary
 * Used to track progress and combine into aggregated summaries
 */
export const threadSummaries = pgTable("thread_summaries", {
  id: serial("id").primaryKey(),
  ticketId: varchar("ticket_id", { length: 255 }).notNull(),
  itemId: varchar("item_id", { length: 255 }).notNull(), // threadId or commentId
  itemIndex: integer("item_index").notNull(), // position in array (0, 1, 2...)
  itemText: text("item_text").notNull(), // original thread/comment text sent to LLM
  summaryText: text("summary_text"), // LLM-generated summary (null until completed)
  totalItems: integer("total_items").notNull(), // total threads or comments for this ticket
  summaryType: varchar("summary_type", { length: 50 }).notNull(), // 'thread' or 'comment'
  processingStatus: varchar("processing_status", { length: 50 }).notNull().default("pending"), // pending, processing, completed, failed
  errorMessage: text("error_message"), // store error if LLM call fails
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
})

/**
 * Stores aggregated summaries for each ticket
 * Three types: 'thread' (all threads combined), 'comment' (all comments combined), 'whole-resolution' (entire ticket)
 * Used to update Vespa after all individual summaries are done
 */
export const ticketAggregatedSummaries = pgTable("ticket_aggregated_summaries", {
  id: serial("id").primaryKey(),
  ticketId: varchar("ticket_id", { length: 255 }).notNull(),
  summaryType: varchar("summary_type", { length: 50 }).notNull(), // 'thread', 'comment', 'whole-resolution'
  finalSummary: text("final_summary"), // final aggregated summary (null until completed)
  processingStatus: varchar("processing_status", { length: 50 }).notNull().default("pending"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
})
