apiVersion: v1
kind: Service
metadata:
  name: {{ include "xyne.fullname" . }}-vespa
  labels:
    {{- include "xyne.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: feed
      port: {{ .Values.vespa.port }}
      targetPort: {{ .Values.vespa.port }}
    - name: query
      port: {{ .Values.vespa.queryPort }}
      targetPort: {{ .Values.vespa.queryPort }}
    - name: config
      port: {{ .Values.vespa.configPort }}
      targetPort: {{ .Values.vespa.configPort }}
  selector:
    {{- include "xyne.vespa.selectorLabels" . | nindent 4 }}
