scrape_configs:
  - job_name: 'vespa-data-ingest'
    scrape_interval: 10s
    metrics_path: /prometheus/v1/values
    static_configs:
      - targets: ['vespa:8080']

  - job_name: 'google_drive_ingestion'
    metrics_path: /metrics  # default path in your Hono app
    scrape_interval: 2s
    static_configs:
      - targets: ['xyne-app:3001']
  # - job_name: 'pm2'
  #   metrics_path: /
  #   scrape_interval: 2s
  #   static_configs:
  #     - targets: ['host.docker.internal:9988']