{
 "title": "Xyne PM2 Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Running application",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm2_available_apps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm2_cpu_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm2_free_memory/1048576", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(__name__, instance, job, serviceName, Value, Time) (pm2_app_instances)"
    },
    {
     "expr": "sum without(__name__, instance, job, serviceName, Value, Time, exported_instance) (pm2_app_status)"
    },
    {
     "expr": "sum without(__name__, instance, job, serviceName) (pm2_app_uptime) / 60 / 60"
    },
    {
     "expr": "sum without(__name__, instance, job, serviceName) (pm2_app_average_memory) / 1048576"
    },
    {
     "expr": "sum without(__name__, instance, job, serviceName) (pm2_app_average_cpu)"
    }
   ]
  },
  {
   "title": "Avg. CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "pm2_app_average_cpu", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Avg. Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "pm2_app_average_memory / 1048576",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "pm2_event_loop_latency_p95", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Available host free memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "pm2_free_memory / 1048576", "legendFormat": "{{app}}" }
   ]
  }
 ]
}