{
 "title": "Xyne Metric Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "email",
    "query": {
     "query": "label_values(google_drive_ingested_total,email)"
    }
   }
  ]
 },
 "panels": [
  { "title": "App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users Email",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(app_request_count) by (email)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chat Count",
   "type": "stat",
   "gridPos": { "h": 14, "w": 7, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "max_over_time(app_request_count{app_endpoint=\"/api/v1/message/create\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search Count",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "increase(app_request_count{app_endpoint=\"/api/v1/search\", offset=\"0\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(app_endpoint,email) (\n  increase(app_request_count{app_endpoint!~\"/auth|/metrics\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(app_endpoint,email) (\n  increase(app_response_count{app_endpoint!~\"/auth|/metrics\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API 4XX and 5XX Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(app_response_count{app_response_status=~\"[45]..\"}[$__rate_interval])",
     "legendFormat": "{{app_endpoint}} : {{app_response_status}}"
    }
   ]
  },
  {
   "title": "Rate of Latency per request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_request_response_duration_seconds_sum[1m]) \n/ \nrate(app_request_response_duration_seconds_count[1m])\n",
     "legendFormat": "{{app_endpoint}}"
    }
   ]
  },
  {
   "title": "Sync by account",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(sync_job_name) ( max_over_time(sync_job_success[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Google Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "% of Google Drive Files Ingested",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(google_drive_ingested_total) / (sum(total_files_to_be_inserted))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Gmail Ingested",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(gmail_ingested_total) / (sum(gmail_to_be_ingested_total_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Counts for Apps",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by(email) (max_over_time(gmail_to_be_ingested_total_count[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(email) (max_over_time(gmail_skipped_from_insertion_count[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(email) (max_over_time(total_files_to_be_inserted[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(user_email) (max_over_time(total_chat_to_be_inserted[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(user_email) (max_over_time(total_convesations_extracted_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gmail Ingest",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(account_type) ( max_over_time(gmail_ingested_total[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(account_type) ( max_over_time(gmail_attachment_ingested_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Entity Ingestion",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(file_type) (( max_over_time(google_drive_ingested_total[$__range])) or max_over_time(google_entity_metadata[$__range]))\n",
     "legendFormat": "SUCCESS"
    }
   ]
  },
  {
   "title": "Google Drive Entity Metric",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum by(file_type) ( max_over_time(google_drive_ingested_total[$__range]))\n",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "# Query C: sum ingestion errors by file_type\nsum by(file_type) (max_over_time(google_drive_ingestion_errors_total[$__range]))",
     "legendFormat": "FAILED"
    },
    {
     "expr": "# Query D: sum EXTRACTED files by file_type\nsum by(file_type) ( max_over_time(google_drive_files_extracted_total[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Query B: sum blocked files by file_type\nsum by(file_type) (max_over_time(google_drive_blocked_files_total[$__range]))\n",
     "legendFormat": "BLOCKED"
    },
    {
     "expr": "# Query E: sum EXTRACTED ERROR files by file_type\nsum by(file_type) ( max_over_time(google_drive_file_extraction_errors_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Insert Conversation Error Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 450 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(job) (insert_conversation_error_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingested Member Error Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 450 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group(ingested_member_error_total_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Team Ingestion Error Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 458 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(domain) (group by(domain) (ingested_member_error_total_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Insert Channel Message Count Error",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 458 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(job) (insert_channel_message_error_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Count of Chat To Be Inserted For a Channel",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 466 },
     "targets": [
      {
       "expr": "sum by(user_email) (max_over_time(total_chat_to_be_inserted[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Conversation To be Inserted Sorted By Email",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 466 },
     "targets": [
      {
       "expr": "sum by(user_email) (max_over_time(total_conversation_inserted_count[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Conversations Skipped From Being Inserted",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 474 },
     "targets": [
      {
       "expr": "sum by(user_email) (max_over_time(total_conversation_skipped_count[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Conversations",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 474 },
     "targets": [
      {
       "expr": "sum by(user_email) (max_over_time(total_convesations_extracted_count[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chat Messages Inserted By Team ID",
     "type": "stat",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 482 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(team_id) (insert_chat_message_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Channel Messages Inserted Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 495 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(job) (insert_channel_message_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Insert Conversation Count",
     "type": "stat",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 495 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(job) (insert_conversation_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Teams By Workspace",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 507 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by(domain) (group by(domain) (ingested_team_total_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Member ingested count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 507 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ingested_member_total_count", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}