FROM vespaengine/vespa:8.554.5
USER root

# Install required tools and matching CUDA ONNX runtime
RUN dnf -y install 'dnf-command(config-manager)' && \
    dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo && \
    dnf -y install $(rpm -q --queryformat '%{NAME}-cuda-%{VERSION}' vespa-onnxruntime) && \
    dnf clean all

USER vespa  # or USER 1000
