FROM vespaengine/vespa:8.514.24

# Switch to root to install packages
USER root

# Install CUDA-enabled ONNX runtime for Vespa
# Using dnf directly as it's the package manager in the base image
RUN dnf -y install dnf-plugins-core


RUN dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo \
 && dnf -y install cuda-libraries-12-2 \
 && dnf clean all


RUN curl -1sLf 'https://dl.cloudsmith.io/public/vespa/open-source-rpms/setup.rpm.sh' | bash && \
    dnf -y install vespa-onnxruntime-cuda-1.20.1 && \
    dnf clean all


# Switch back to vespa user (UID 1000 is typical for vespaengine/vespa)
USER 1000
