server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pm2-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: pm2
          service_name: xyne-server
          __path__: /pm2-logs/xyne-server-*.log

  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: xyne-app
          service_name: xyne-server
          __path__: /app-logs/*.log
