{
 "title": "Xyne Metrics",
 "tags": [
  "prometheus",
  "grafana"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Documents ingested in total vs time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "content_proton_documentdb_documents_total_max",
     "legendFormat": "documents_ingested"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "content_proton_resource_usage_memory_average{}",
     "legendFormat": "Memory usage average"
    }
   ]
  },
  {
   "title": "Avg Results per search",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "content_proton_search_protocol_query_latency_average{}"
    }
   ]
  },
  {
   "title": "Query Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_search_protocol_query_latency_average{}",
     "legendFormat": "active_appenders"
    }
   ]
  },
  {
   "title": "Max Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_search_protocol_query_latency_max",
     "legendFormat": "query_latency"
    }
   ]
  },
  {
   "title": "Document Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_search_protocol_docsum_requested_documents_rate{}",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "Vespa GC Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jdisc_gc_ms_average{}", "legendFormat": "duration-p99" }
   ]
  },
  {
   "title": "HTTP Req Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(http_status_2xx_rate[1m])", "legendFormat": "duration-{{p99}}" }
   ]
  },
  {
   "title": "Max Disk Utilised",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cluster_controller_resource_usage_max_disk_utilization_max{}",
     "legendFormat": "disk_space"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "cpu_util{}", "legendFormat": "data_files" }
   ]
  },
  {
   "title": "Avg Free Heap Memory",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mem_heap_free_average{}", "legendFormat": "free-heap-meme" }
   ]
  },
  {
   "title": "Average Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_resource_usage_disk_average{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}