version: '3.8'

services:
  # Configuration server (required for multi-node cluster)
  vespa-config:
    image: vespaengine/vespa:8.431.26
    container_name: vespa-config
    hostname: vespa-config
    ports:
      - "19071:19071"  # Config server port
      - "19050:19050"  # Admin port
    volumes:
      - ./:/opt/vespa/var/db/vespa/config_server/serverdb/tenants/default/sessions/1/
      - vespa-config-data:/opt/vespa/var/db/vespa
    environment:
      - VESPA_CONFIGSERVERS=vespa-config
    command: ["/opt/vespa/bin/vespa-start-configserver"]
    networks:
      - vespa-cluster

  # Node 1 - Primary content node  
  vespa-node1:
    image: vespaengine/vespa:8.431.26
    container_name: vespa-node1
    hostname: vespa-node1
    ports:
      - "8080:8080"   # Query/feed port
      - "19112:19112" # Status port
    volumes:
      - ./:/opt/vespa/var/db/vespa/config_server/serverdb/tenants/default/sessions/1/
      - vespa-node1-data:/opt/vespa/var/db/vespa
    environment:
      - VESPA_CONFIGSERVERS=vespa-config
    depends_on:
      - vespa-config
    command: ["/opt/vespa/bin/vespa-start-services"]
    networks:
      - vespa-cluster

  # Node 2 - Secondary content node (for redundancy)
  vespa-node2:
    image: vespaengine/vespa:8.431.26
    container_name: vespa-node2
    hostname: vespa-node2
    ports:
      - "8081:8080"   # Query/feed port (different host port)
      - "19113:19112" # Status port (different host port)
    volumes:
      - ./:/opt/vespa/var/db/vespa/config_server/serverdb/tenants/default/sessions/1/
      - vespa-node2-data:/opt/vespa/var/db/vespa
    environment:
      - VESPA_CONFIGSERVERS=vespa-config
    depends_on:
      - vespa-config
    command: ["/opt/vespa/bin/vespa-start-services"]
    networks:
      - vespa-cluster

volumes:
  vespa-config-data:
  vespa-node1-data:
  vespa-node2-data:

networks:
  vespa-cluster:
    driver: bridge