#!/bin/sh

# Added to integrate Commitizen for standardized commit messages
# Additional logic to prevent infinite loops, setting CZ_SKIP_HOOK environment variable to 1 when commitzen is invoked
if [ -z "$CZ_SKIP_HOOK" ]; then
  export CZ_SKIP_HOOK=1
  cd server
  exec < /dev/tty bunx cz
fi

