name: version-build-release

on:
  push:
    branches:
      - main 

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./server
        run: bun install

      - name: Get GitHub App Token
        id: github-app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.XYNE_RELEASE_APP_ID }}
          private_key: ${{ secrets.XYNE_RELEASE_APP_SECRET }}
          installation_retrieval_mode: "repository"
          installation_retrieval_payload: ${{ github.repository }}

      - name: Run semantic-release
        id: semantic
        working-directory: ./server
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ steps.github-app-token.outputs.token }}
          GH_TOKEN: ${{ steps.github-app-token.outputs.token }}
        run: bunx semantic-release --no-ci

      - name: Extract release version
        id: get_version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo "version=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v6
        with:
          # Adjust if your Dockerfile is inside ./server
          context: ../../
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/xynehq/xyne:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/xynehq/xyne:${{ steps.get_version.outputs.version }}
