name: TypeScript Build Check

on:
  pull_request:
    branches: [ main ]  # Adjust this as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Dependencies (Frontend)
      working-directory: ./frontend
      run: bun install

    - name: Install Dependencies (Server)
      working-directory: ./server
      run: bun install

    - name: TypeScript Build Check (Frontend)
      working-directory: ./frontend
      run: bunx tsc -b

    - name: TypeScript Build Check (Server)
      working-directory: ./server
      run: bunx tsc -b